version: '3'

services:
  server:
    image: deminy/swoole-by-examples:server
    environment:
      SWOOLE_EXT_ASYNC: enabled
      SWOOLE_EXT_ORM: enabled
      SWOOLE_EXT_POSTGRESQL: enabled
      SWOOLE_EXT_SERIALIZE: enabled
      SWOOLE_EXT_ZOOKEEPER: enabled
      AUTORELOAD_PROGRAMS: "http1 http1-advanced http2 keepalive mixed-protocols-1 pool-msgqueue pool-tcp-socket pool-unix-socket redis tcp1 udp websocket"
    volumes:
      - ./examples:/var/www
      - ./rootfilesystem/etc/supervisor/service.d:/etc/supervisor/service.d
  client:
    image: deminy/swoole-by-examples:client
    environment:
      DISABLE_DEFAULT_SERVER: 1
    links:
      - server
    volumes:
      - ./examples:/var/www
