version: '3'

services:
  app:
    image: phpswoole/swoole
    environment:
      SWOOLE_EXT_ASYNC: enabled
      SWOOLE_EXT_ORM: enabled
      SWOOLE_EXT_POSTGRESQL: enabled
      SWOOLE_EXT_SERIALIZE: enabled
      AUTORELOAD_PROGRAMS: "http1 websocket tcp mixed-protocols-1"
    volumes:
      - ./examples:/var/www
      - ./rootfilesystem/etc/supervisor/service.d:/etc/supervisor/service.d
    ports:
      - 9501:9501
      - 9503:9503
      - 9504:9504
      - 9511:9511
