version: '3'

services:
  server:
    image: deminy/swoole-by-examples:server
    environment:
      AUTORELOAD_PROGRAMS: "http1 http1-integrated http2 keepalive mixed-protocols-1 pool-msgqueue pool-tcp-socket pool-unix-socket redis tcp1 tcp2 udp websocket"
    volumes:
      - ./examples:/var/www
  client:
    image: deminy/swoole-by-examples:client
    environment:
      DISABLE_DEFAULT_SERVER: 1
    links:
      - mysql
      - server
    volumes:
      - ./examples:/var/www
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: username
