name: Build Docker Images

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'deminy/swoole-by-examples' }}
    strategy:
      fail-fast: true
      matrix:
        type: ["server", "client"]

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and Publish Versioned Couchbase Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./dockerfiles/${{ matrix.type }}/
          platforms: linux/amd64
          push: true
          tags: deminy/swoole-by-examples:${{ matrix.type }}

      -
        name: Image Digest of deminy/couchbase:${{ steps.params.outputs.docker_tag }}
        run: echo ${{ steps.docker_build.outputs.digest }}
