name: Coding Style Checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          version: 2

      - name: Run Coding Style Checks
        run: ./vendor/bin/phpcs -v --standard=ruleset.xml examples
