name: Coding Style Checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  coding-style-checks:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Coding Style Checks
        run: docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php8.2 php-cs-fixer fix --dry-run
