name: Static Analysis

on: [ push, pull_request, workflow_dispatch ]

jobs:
  static-analysis:
    runs-on: ubuntu-22.04
    container:
      image: deminy/swoole-by-examples:server-5.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP And Swoole
        run: |
          set -e
          echo "swoole.enable_library=Off" >> /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini
          composer global require -n -q --no-progress -- \
            phpstan/phpstan=^1.11.x-dev \
            predis/predis=~2.2 \
            swoole/library=~5.0

      - name: Run Static Analysis
        run: ~/.composer/vendor/bin/phpstan analyse --no-progress --memory-limit 2G
