name: Static Analysis

on: [ push, pull_request, workflow_dispatch ]

jobs:
  static-analysis:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: redis-stable, swoole-5.1.1, sysvmsg
          ini-values: swoole.enable_library=off
          coverage: none
        env:
          SWOOLE_CONFIGURE_OPTS: --enable-mysqlnd --enable-swoole-pgsql --enable-openssl --enable-sockets --enable-swoole-curl

      - name: Install PHPStan
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: |
            set -ex
            composer global require phpstan/phpstan=^1.11.x-dev -n -q --no-progress
            composer global require predis/predis=~2.2 -n -q --no-progress
            composer global require swoole/library=~5.0 -n -q --no-progress

      - name: Run Static Analysis
        run: ~/.composer/vendor/bin/phpstan analyse --no-progress --memory-limit 2G
